###
POST http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{
    "name": "Ezequiel",
    "age": 83,
    "email": "pepito.com",
    "picture": "https://imgs.search.brave.com/whyckyrJ17qnooltpTq_YA60G3fIKndzI9J8JNMgKWY/rs:fit:860:0:0/g:ce/aHR0cHM6Ly9ldmFv/cnRpei5lcy93cC1j/b250ZW50L3VwbG9h/ZHMvMjAxOS8wMS9u/b2VsaWEtcG9zdC0x/LTMwMHgyMjguanBn"

}
###
GET http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{}

###
GET http://localhost:3000/users/660ffd20c5e138ebfd136321 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:3000/users/660ffd20c5e138ebfd136321 HTTP/1.1
Content-Type: application/json

{
    "name": "Ezequiel Actualizado",
    "age": 100,
    "email": "pepito.actualizado.com"
}

### 
DELETE http://localhost:3000/users/660ffd20c5e138ebfd136321 HTTP/1.1
Content-Type: application/json