###
POST https://api-user-list.onrender.com/users HTTP/1.1
Content-Type: application/json

{
    "name": "Ezequiel2",
    "age": 83,
    "email": "pepito.com",
    "picture": "https://imgs.search.brave.com/9B4B0npB9UuaVucFOq-IuOvQqL0rTMXvnH6OTjIVX0Q/rs:fit:500:0:0/g:ce/aHR0cHM6Ly9idWZm/ZXIuY29tL2xpYnJh/cnkvY29udGVudC9p/bWFnZXMvMjAyMi8w/My9za2l0Y2gtLTct/LnBuZw"
}
###
GET http://localhost:3000/users HTTP/1.1
Content-Type: application/json

{}

###
GET http://localhost:3000/users/660ffd20c5e138ebfd136321 HTTP/1.1
Content-Type: application/json

###
PUT http://localhost:3000/users/6610625ae48b31ba18ef873a HTTP/1.1
Content-Type: application/json

{
    "name": "Ezequiel Actualizado",
    "age": 100,
    "email": "pepito.actualizado.com"
}

### 
DELETE https://api-user-list.onrender.com/users/6610625ae48b31ba18ef873a  HTTP/1.1
Content-Type: application/json